// src/app/api/generate-website/route.js

export async function POST(req) {
  try {
    const { prompt, template, style } = await req.json();

    if (!prompt || prompt.trim() === '') {
      return Response.json({ error: 'Prompt is required' }, { status: 400 });
    }

    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      console.error('GEMINI_API_KEY is not set');
      return Response.json({ 
        error: 'API key not configured. Please add GEMINI_API_KEY to Vercel environment variables.' 
      }, { status: 500 });
    }

    console.log('Generating website with Gemini API...');

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: `You are an expert web developer. Create a complete, production-ready, single-page ${template || 'custom'} website.

User Request: ${prompt}

Design Style: ${style || 'modern'}

CRITICAL REQUIREMENTS:
1. Return ONLY complete HTML code starting with <!DOCTYPE html>
2. Embed ALL CSS in a <style> tag inside <head>
3. Embed ALL JavaScript in a <script> tag before </body>
4. NO external dependencies, NO CDN links, NO imports
5. Use inline placeholder images: https://placehold.co/WIDTHxHEIGHT
6. Make it fully responsive (mobile, tablet, desktop)
7. Use modern CSS: flexbox, grid, gradients, shadows, animations
8. Add smooth scrolling and hover effects
9. Use a professional color scheme that matches the ${style || 'modern'} style
10. Include realistic content, not just placeholders

TEMPLATE GUIDELINES:
${getTemplateGuidelines(template)}

Return ONLY the HTML code. No explanations, no markdown code blocks, no additional text. Just pure HTML starting with <!DOCTYPE html>`
            }]
          }],
          generationConfig: {
            temperature: 0.8,
            maxOutputTokens: 8192,
          }
        })
      }
    );

    const data = await response.json();

    if (!response.ok) {
      console.error('Gemini API Error:', data);
      return Response.json({ 
        error: data.error?.message || 'Failed to generate website with Gemini API' 
      }, { status: 500 });
    }

    let htmlCode = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!htmlCode) {
      console.error('No content in Gemini response:', data);
      return Response.json({ 
        error: 'No content generated by AI' 
      }, { status: 500 });
    }

    const tripleBacktickHTML = String.fromCharCode(96, 96, 96) + 'html';
    const tripleBacktick = String.fromCharCode(96, 96, 96);
    
    htmlCode = htmlCode.split(tripleBacktickHTML).join('');
    htmlCode = htmlCode.split(tripleBacktick).join('');
    htmlCode = htmlCode.trim();

    if (!htmlCode.toLowerCase().includes('<!doctype html>')) {
      console.warn('Generated code missing DOCTYPE, adding it...');
      htmlCode = '<!DOCTYPE html>\n' + htmlCode;
    }

    console.log('Website generated successfully!');

    const websiteData = {
      id: Date.now().toString(),
      html: htmlCode,
      metadata: {
        prompt,
        template: template || 'custom',
        style: style || 'modern',
        created_at: new Date().toISOString(),
        generator: 'Google Gemini 1.5 Flash'
      }
    };

    return Response.json(websiteData);

  } catch (error) {
    console.error('Error generating website:', error);
    return Response.json({ 
      error: 'Failed to generate website: ' + error.message 
    }, { status: 500 });
  }
}

function getTemplateGuidelines(template) {
  const guidelines = {
    portfolio: `
- Hero section with name/title and professional photo placeholder
- About section with bio
- Portfolio/Projects grid with 6-9 project cards
- Skills section with visual skill bars or icons
- Contact section with form
- Smooth scroll navigation
- Use elegant typography and professional colors`,

    business: `
- Hero section with company tagline and CTA button
- Services/Features section with icon cards (3-6 services)
- About/Why Choose Us section
- Testimonials section with customer quotes
- Call-to-action section
- Footer with contact info
- Professional corporate color scheme`,

    ecommerce: `
- Header with logo and navigation
- Featured products grid (8-12 products)
- Product cards with image, name, price, Add to Cart button
- Categories section
- Special offers/deals banner
- Shopping cart icon in header
- Modern e-commerce styling with good product imagery`,

    restaurant: `
- Hero section with restaurant name and appetizing food image
- Menu sections (Appetizers, Main Courses, Desserts, Drinks)
- Each menu item with name, description, price
- About/Story section
- Hours and Location section
- Reservation CTA button
- Warm, inviting colors (reds, oranges, browns)`,

    custom: `
- Create an appropriate layout based on the user description
- Include all relevant sections for the requested website type
- Use intuitive navigation
- Professional and modern design`
  };

  return guidelines[template] || guidelines.custom;
}
